import fs from "node:fs";
import path from "node:path";
import { build } from "esbuild";
import postcss from "postcss";
import tailwindcss from "tailwindcss";

const root = path.resolve(import.meta.dirname, "..");
const dist = path.join(root, "dist");
fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(path.join(dist, "adapters"), { recursive: true });

const tailwindResult = await postcss([
    tailwindcss({
        content: [
            path.join(root, "src/browser/legacy/ui-view.js"),
            path.join(root, "src/browser/legacy/ui-adhoc.js"),
            path.join(root, "src/browser/legacy/runtime.js")
        ],
        important: "#scenario-test-root",
        theme: { extend: {} },
        plugins: []
    })
]).process("@tailwind base; @tailwind components; @tailwind utilities;", { from: undefined });
fs.writeFileSync(
    path.join(root, "src/browser/tailwind.generated.js"),
    `// Generated by scripts/build.mjs.\nexport const TAILWIND_CSS = ${JSON.stringify(tailwindResult.css)};\n`,
    "utf8"
);

const shared = {
    bundle: true,
    sourcemap: true,
    legalComments: "inline",
    logLevel: "info",
    banner: { js: "/*! scenario-test v0.1.0 */" }
};

await build({
    ...shared,
    entryPoints: [path.join(root, "src/index.js")],
    outfile: path.join(dist, "scenario-test.umd.js"),
    platform: "browser",
    format: "iife",
    globalName: "ScenarioTest",
    target: ["chrome100"]
});

await build({
    ...shared,
    entryPoints: [path.join(root, "src/index.js")],
    outfile: path.join(dist, "scenario-test.esm.js"),
    platform: "browser",
    format: "esm",
    target: ["es2020"]
});

await build({
    ...shared,
    entryPoints: [path.join(root, "src/node.js")],
    outfile: path.join(dist, "scenario-test.cjs"),
    platform: "node",
    format: "cjs",
    target: ["node18"]
});

await build({
    ...shared,
    entryPoints: [path.join(root, "src/cli.js")],
    outfile: path.join(dist, "scenario-test-cli.cjs"),
    platform: "node",
    format: "cjs",
    target: ["node18"]
});

await build({
    ...shared,
    entryPoints: [path.join(root, "src/adapters/xlsx.js")],
    outfile: path.join(dist, "adapters/xlsx.cjs"),
    platform: "node",
    format: "cjs",
    target: ["node18"]
});
