import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { build } from "esbuild";
import postcss from "postcss";
import tailwindcss from "tailwindcss";

const root = path.resolve(import.meta.dirname, "..");
const dist = path.join(root, "dist");
const packageInfo = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
fs.writeFileSync(
    path.join(root, "src/version.generated.js"),
    `// Generated by scripts/build.mjs from package.json.\nexport const VERSION = ${JSON.stringify(packageInfo.version)};\n`,
    "utf8"
);
fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist, { recursive: true });

// 版本写入后动态导入 contract（获得最新 VERSION），生成对外能力清单与 d.ts
const { contract } = await import(pathToFileURL(path.join(root, "src/contract.js")).href);
const { buildCapabilities } = await import(pathToFileURL(path.join(root, "src/capabilities.js")).href);
const capabilities = buildCapabilities(contract);
const capabilitiesJson = `${JSON.stringify(capabilities, null, 2)}\n`;
fs.writeFileSync(path.join(dist, "scenario-test-capabilities.json"), capabilitiesJson, "utf8");

await import(pathToFileURL(path.join(root, "scripts/generate-dts.mjs")).href);

const tailwindResult = await postcss([
    tailwindcss({
        content: [
            path.join(root, "src/browser/legacy/ui-view.js"),
            path.join(root, "src/browser/legacy/ui-adhoc.js"),
            path.join(root, "src/browser/legacy/runtime.js")
        ],
        important: "#scenario-test-root",
        theme: { extend: {} },
        plugins: []
    })
]).process("@tailwind base; @tailwind components; @tailwind utilities;", { from: undefined });
fs.writeFileSync(
    path.join(root, "src/browser/tailwind.generated.js"),
    `// Generated by scripts/build.mjs.\nexport const TAILWIND_CSS = ${JSON.stringify(tailwindResult.css)};\n`,
    "utf8"
);

const shared = {
    bundle: true,
    sourcemap: true,
    legalComments: "inline",
    logLevel: "info",
    banner: { js: `/*! scenario-test v${packageInfo.version} */` }
};

await build({
    ...shared,
    entryPoints: [path.join(root, "src/index.js")],
    outfile: path.join(dist, "scenario-test.umd.js"),
    platform: "browser",
    format: "iife",
    globalName: "ScenarioTest",
    target: ["chrome100"]
});

await build({
    ...shared,
    entryPoints: [path.join(root, "src/index.js")],
    outfile: path.join(dist, "scenario-test.esm.js"),
    platform: "browser",
    format: "esm",
    target: ["es2020"]
});

await build({
    ...shared,
    entryPoints: [path.join(root, "src/node.js")],
    outfile: path.join(dist, "scenario-test.cjs"),
    platform: "node",
    format: "cjs",
    target: ["node18"]
});

await build({
    ...shared,
    entryPoints: [path.join(root, "src/cli.js")],
    outfile: path.join(dist, "scenario-test-cli.cjs"),
    platform: "node",
    format: "cjs",
    target: ["node18"],
    // CLI 产物作为 npm bin：需要 shebang 才能被 npx/命令行直接执行
    banner: { js: `#!/usr/bin/env node\n/*! scenario-test v${packageInfo.version} */` }
});
