// 从 src/contract.js 投影生成 dist/scenario-test.d.ts
//
// - 操作符/保留变量/类型名单（AssertionOperator、ReservedVar、GeneratedVarType 等）
//   由 contract 投影生成，禁止手工复制名单导致漂移；构建/测试会校验一致。
// - 手写部分仅为公共 API 形状（函数签名、接口结构）。
// - 文件头部保留运行时与 contract 版本标记，便于识别构建产物。
// - 输出目录可用 --out <dir> 覆盖（build.mjs 传 staging 目录做原子交换），默认 dist。
import fs from "node:fs";
import path from "node:path";
import { contract } from "../src/contract.js";

const root = path.resolve(import.meta.dirname, "..");
const outArg = process.argv[process.argv.indexOf("--out") + 1];
const dist = outArg ? path.resolve(root, outArg) : path.join(root, "dist");

const quote = (list) => list.map((item) => JSON.stringify(item)).join(" | ");
const operatorNames = Object.keys(contract.assertions.operators);

// 断言操作符接口成员：由 contract 投射（含 JSDoc 描述），禁止手写第二份操作符名单
const valueTypeToTs = {
    boolean: "boolean",
    any: "unknown",
    string: "string",
    array: "unknown[]",
    finiteNumber: "number",
    assertion: "Assertion | Assertion[]"
};

const operatorMembers = (indent) => Object.entries(contract.assertions.operators).map(([name, spec]) => {
    const tsType = valueTypeToTs[spec.valueType];
    if (!tsType) throw new Error(`contract 操作符 ${name} 的 valueType "${spec.valueType}" 缺少 d.ts TS 类型映射`);
    return `${indent}/** ${spec.description} */\n${indent}${name}?: ${tsType};`;
}).join("\n");

const dts = `// scenario-test v${contract.runtimeVersion}（contract v${contract.contractVersion}）
// Generated by scripts/generate-dts.mjs from src/contract.js — Do not edit manually.
// 操作符/保留变量/类型名单由 contract 投影生成；其余为公共 API 形状。

export type AssertionOperator = ${quote(operatorNames)};
export type NumericAssertionOperator = ${quote(contract.assertions.numericOperators)};
export type AssertionMetaKey = ${quote(contract.assertions.metaKeys)};
export type ReservedVar = ${quote(contract.reservedVars)};
export type GeneratedVarType = ${quote(contract.generatedVars.types)};
export type GlobalParamType = ${quote(contract.globals.types)};
export type WhenSource = ${quote(contract.when.sources)};
export type ExtractSource = ${quote(contract.extract.from)};
export type FailurePolicy = ${quote(contract.scenario.failurePolicies)};

export interface GlobalParam {
    type: GlobalParamType;
    name: string;
    value?: unknown;
}

export interface Environment {
    key: string;
    name: string;
    baseUrl?: string;
    globals?: GlobalParam[];
    authorization?: string;
}

export interface ConfigVariable {
    name: string;
    label?: string;
    env?: string;
    required?: boolean;
    defaultValue?: unknown;
}

/** scenario.config.js 的 scenarios 清单项；manual: true 表示需要人工准备数据（--all 默认排除） */
export interface ScenarioListItem {
    id: string;
    name?: string;
    url: string;
    manual?: boolean;
    /** 兼容回退字段（等价 url） */
    file?: string;
    path?: string;
}

export interface ScenarioConfig {
    envs?: Environment[];
    defaultEnvKey?: string;
    globals?: GlobalParam[];
    vars?: Record<string, unknown>;
    scenarioVars?: Record<string, unknown>;
    variables?: ConfigVariable[];
    scenarios?: ScenarioListItem[];
    requestTimeoutMs?: number;
    storagePrefix?: string;
    baseUrl?: string;
    authorization?: string;
    nodePlugins?: string[];
}

/** 断言定义：元数据键 + 至少一个操作符；gt/gte/lt/lte/length 只接受有限 number；target 可取 status/duration */
export interface Assertion {
    name?: string;
    path?: string;
    from?: "vars" | "headers" | "bodyText";
    target?: "status" | "duration";
    header?: string;
    implicit?: boolean;
${operatorMembers("    ")}
}

export interface ExtractDefinition {
    name: string;
    path?: string;
    from?: ExtractSource;
    /** required: true 且路径不存在时当前步骤失败；默认缺失产生 warning */
    required?: boolean;
}

/** when 对象形式：from 只能取 vars（来自 contract.when.sources） */
export interface WhenDefinition {
    from: WhenSource;
    path?: string;
${operatorMembers("    ")}
}

export interface GeneratedVarDefinition {
    name: string;
    type: GeneratedVarType;
    parts?: string[];
    params?: Record<string, string>;
    secretVar?: string;
    /** idcard 专用：出生日期 YYYY-MM-DD（必填） */
    birthDate?: string;
    /** idcard 专用：MALE/FEMALE，默认 MALE */
    gender?: string;
    /** idcard/uscc 专用：6 位行政区划（idcard 缺省从测试区划池按轮次派生；uscc 默认 110100） */
    regionCode?: string;
    /** luhn 专用：卡号长度 12-19，默认 16 */
    length?: number;
    /** luhn 专用：数字卡头（默认 "62"）；phone 专用：3 位号段 1[3-9]x（缺省从测试号段池按轮次派生） */
    prefix?: string;
}

export interface RetryUntil {
    /** 最大尝试总次数（含首次请求），默认 10；两次尝试之间至少间隔 100ms */
    maxAttempts?: number;
    intervalMs?: number;
    maxElapsedMs?: number;
}

export interface RequestDefinition {
    headers?: Record<string, string>;
    body?: unknown;
    credentials?: "include" | "omit" | "same-origin";
    redirect?: "follow" | "error" | "manual";
    fileUpload?: unknown;
    useEnvironmentAuthorization?: boolean;
}

export interface Step {
    name: string;
    method?: string;
    path?: string;
    params?: Record<string, unknown>;
    request?: RequestDefinition;
    status?: number;
    assertions?: Assertion[];
    extract?: ExtractDefinition[];
    when?: WhenDefinition | string | boolean;
    retryUntil?: RetryUntil;
    timeoutMs?: number;
    saveResponseAs?: string;
    adapter?: string;
    /** 适配器专属步骤键与兼容字段 */
    [key: string]: unknown;
}

export interface ScenarioDefinition {
    name: string;
    steps: Step[];
    vars?: Record<string, unknown>;
    envVars?: Record<string, string>;
    generatedVars?: GeneratedVarDefinition[];
    failurePolicy?: FailurePolicy;
}

// each 操作符的失败元素明细：index 为失败元素在数组中的下标（0 基），
// actual 为该元素值，assertions 为该元素上全部子断言的求值结果
// （嵌套 each 的子结果同样是 AssertionResult，失败时携带各自的 detail）
export interface AssertionEachFailure {
    index: number;
    actual?: unknown;
    assertions: AssertionResult[];
}

export interface AssertionResult {
    name: string;
    passed: boolean;
    actual?: unknown;
    expected?: unknown;
    detail?: AssertionEachFailure[];
}

export interface ScenarioStepResult {
    name: string;
    method: string;
    path: string;
    status: number | string;
    duration: number;
    passed: boolean;
    skipped?: boolean;
    cancelled?: boolean;
    timedOut?: boolean;
    error?: string;
    warnings?: string[];
    assertions: AssertionResult[];
    stepNo?: number;
    request?: unknown;
    response?: unknown;
}

export interface ScenarioReport {
    scenarioName: string;
    passed: boolean;
    status: "PASSED" | "FAILED" | "SKIPPED" | "CANCELLED";
    planned: number;
    executed: number;
    passedSteps: number;
    failed: number;
    skipped: number;
    results: ScenarioStepResult[];
    vars: Record<string, unknown>;
}

export interface Runtime {
    vars: Record<string, unknown>;
    lastResponse: unknown;
    lastResponseBody: unknown;
}

export interface EngineOptions {
    config?: ScenarioConfig;
    baseUrl?: string;
    authorization?: string;
    globals?: GlobalParam[];
    vars?: Record<string, unknown>;
    environmentVariables?: Record<string, string | undefined>;
    fetch?: typeof globalThis.fetch;
    requestTimeoutMs?: number;
    adapters?: Record<string, unknown>;
    isolateAdapters?: boolean;
    signal?: AbortSignal;
    verboseErrors?: boolean;
}

export interface RunOptions {
    config?: ScenarioConfig;
    vars?: Record<string, unknown>;
    environmentVariables?: Record<string, string | undefined>;
    signal?: AbortSignal;
    onStep?: (result: ScenarioStepResult, index: number, runtime: Runtime) => void | Promise<void>;
}

export interface Engine {
    runScenario(scenario: ScenarioDefinition, options?: RunOptions): Promise<ScenarioReport>;
    runStep(step: Step, runtime: Runtime, options?: RunOptions): Promise<ScenarioStepResult>;
    createRuntime(scenario: ScenarioDefinition, options?: unknown): Runtime;
}

/** 浏览器工作台实例（createApp 返回值）：覆盖三方常用入口 */
export interface ScenarioApp {
    loadScenario(idOrUrl: string): Promise<unknown>;
    runAll(): Promise<unknown>;
    runNext(): Promise<unknown>;
    reset(): void;
    cancel(): void;
    rewindToStep(stepNo: number): void;
    rerunStep(stepNo: number): void;
    destroy(): void;
    getState(): unknown;
}

export function defineConfig(input: ScenarioConfig): ScenarioConfig;
export function registerConfig(config: ScenarioConfig): ScenarioConfig;
export function getConfig(): ScenarioConfig | null;
export function defineScenario(input: ScenarioDefinition): ScenarioDefinition;
export function registerScenario(id: string, scenario: ScenarioDefinition): ScenarioDefinition;
export function getScenario(id: string): ScenarioDefinition | undefined;
export function clearScenarios(): void;
export function registerAdapter(name: string, adapter: unknown): unknown;
export function getAdapter(name: string): unknown;
export function listAdapters(): Map<string, unknown>;
export function createEngine(options?: EngineOptions): Engine;
export function runScenario(scenario: ScenarioDefinition, options?: RunOptions): Promise<ScenarioReport>;
export function createApp(options: { mount: string | Element; config?: ScenarioConfig }): ScenarioApp;

export function validateAssertion(definition: Assertion, context?: unknown): Assertion;
export function evaluateAssertion(definition: Assertion, response: unknown, runtime: unknown, context?: unknown): AssertionResult;
export function applyExtract(step: { extract?: ExtractDefinition[] }, response: unknown, runtime: Runtime): { warnings: string[]; failures: AssertionResult[] };
export function buildAssertions(step: Step, response: unknown, runtime: unknown, context?: unknown): AssertionResult[];
export function resolve(value: unknown, runtime: unknown): unknown;
export function joinUrl(baseUrl: string, requestPath: string): string;
export function buildUrl(requestPath: string, params?: Record<string, unknown>, runtime?: unknown): string;
export function generateSignature(params: Record<string, unknown>, secretValue: string): string;
export function md5(value: unknown): string;
export function clone<T>(value: T): T;
export function formatDuration(milliseconds: number): string;

export const VERSION: string;
export const CONTRACT_VERSION: number;
export const RESERVED_VARS: readonly string[];
export const ASSERTION_OPERATORS: readonly string[];
export const ASSERTION_META_KEYS: readonly string[];
export const GLOBAL_TYPES: readonly string[];

export declare const contract: {
    contractVersion: number;
    runtimeVersion: string;
    assertions: {
        metaKeys: readonly AssertionMetaKey[];
        targets: readonly string[];
        operators: Record<AssertionOperator, { description: string; valueType: string }>;
        numericOperators: readonly NumericAssertionOperator[];
    };
    when: { sources: readonly WhenSource[]; note: string };
    extract: { from: readonly ExtractSource[]; required: string; note: string };
    reservedVars: readonly ReservedVar[];
    generatedVars: { types: readonly GeneratedVarType[] };
    globals: { types: readonly GlobalParamType[]; note: string };
    config: {
        scenarioItemKeys: readonly string[];
        environmentKeys: readonly string[];
        variableKeys: readonly string[];
        manual: { type: string; note: string };
    };
    scenario: {
        keys: readonly string[];
        stepKeys: readonly string[];
        failurePolicies: readonly FailurePolicy[];
    };
    cli: {
        commands: readonly string[];
        options: Record<string, { kind: "value" | "flag"; prop: string; description: string; aliases?: readonly string[] }>;
    };
};

export as namespace ScenarioTest;
`;

fs.mkdirSync(dist, { recursive: true });
fs.writeFileSync(path.join(dist, "scenario-test.d.ts"), dts, "utf8");
console.log(`已生成 dist/scenario-test.d.ts（v${contract.runtimeVersion}，contract v${contract.contractVersion}）`);